# Generated by Django 3.2.5 on 2021-09-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210930_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uploadedFile',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
