# Generated by Django 3.2.6 on 2021-09-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uploadedFile',
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
