# Generated by Django 3.2.6 on 2021-10-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211008_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='time',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
